apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: wp-front
  template:
    metadata:
      labels:
        app: wp-front
    spec:
      containers:
      - name: wp
        image: wordpress:5.1.1-php7.3-apache
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
  replicas: 2

---

apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  selector:
    app: wp-front 
  ports:
  - port: 32323
    targetPort: 80
  type: LoadBalancer
